name: Go Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: amd64
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: amd64
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.3'

      - name: Build
        run: |
          go build -v -o udrive-${{ matrix.os }}-${{ matrix.arch }} ./...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: go test -v ./...

      - name: Upload artifact (build artifact)
        uses: actions/upload-artifact@v7
        with:
          name: udrive-${{ matrix.os }}-${{ matrix.arch }}
          path: udrive-${{ matrix.os }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v7
        with:
          path: dist
          merge-multiple: true

      - name: Create & publish GitHub Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*
          generate_release_notes: true